language: java
jdk:
- openjdk7
env:
  global:
  - INTEGRATION_LOGFILE=/var/tmp/aspace-integration.log
  - DISPLAY=:99.0
  - SCREENSHOT_ON_ERROR=1
  matrix:
  - DB=derby TASK=travis:selenium
before_install:
- /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile
  --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 2560x1700x24
- export DISPLAY=:99.0
before_script:
- sleep 3
- if [[ "$DB" == "mysql" ]]; then (mkdir lib; cd lib; curl -Oq http://central.maven.org/maven2/mysql/mysql-connector-java/5.1.34/mysql-connector-java-5.1.34.jar);
  fi
- if [[ "$DB" == "mysql" ]]; then export JAVA_OPTS="-Daspace.config.db_url=jdbc:mysql://localhost:3306/archivesspace?useUnicode=true&characterEncoding=UTF-8&user=root";
  fi
- if [[ "$DB" == "mysql" ]]; then mysql -e "create database archivesspace default
  character set utf8;"; fi
branches:
  except:
  - gh-pages
script:
- build/run $TASK
notifications:
  irc: irc.freenode.org#archivesspace
  email: false
addons:
  artifacts:
    debug: true
    bucket: astravisartifacts 
    paths:
    - $( ls /var/tmp/*.png | tr "\n" ":" )
    - $( ls /tmp/*.png | tr "\n" ":" )
    - $( sudo ls /var/log/mysql/* | tr "\n" ":" )
    - $( ls  /var/tmp/aspace-integration.log | tr "\n" ":" )
